/**
 * McKinsey-style slide presentation component
 * Layout: 2/3 chart + 1/3 commentary with Minto Pyramid insights
 */

import { ChartRenderer } from '@/features/chart/components/ChartRenderer'
import type { ChartConfiguration } from '@/shared/types/chart'
import type { SlideContent } from '../utils/slideGenerator'

interface SlidePresentationProps {
  config: ChartConfiguration
  slideContent: SlideContent
}

export function SlidePresentation({ config, slideContent }: SlidePresentationProps) {
  const { title, subtitle, chartTitle, chartUnits, insights } = slideContent

  return (
    <div className="w-full h-full bg-white flex flex-col">
      {/* Slide Header */}
      <div className="border-b-4 border-[#003d7a] px-10 py-6 flex-shrink-0">
        <h1 className="text-3xl font-bold text-[#003d7a] mb-1">
          {title}
        </h1>
        {subtitle && (
          <h2 className="text-lg text-gray-600 font-normal">
            {subtitle}
          </h2>
        )}
      </div>

      {/* Main Content: 2/3 Chart + 1/3 Commentary */}
      <div className="flex-1 flex gap-8 px-10 py-8 min-h-0">
        {/* Chart Section (2/3) */}
        <div className="flex-[2] flex flex-col min-w-0">
          <div className="mb-3">
            <h3 className="text-base font-bold text-gray-800">
              {chartTitle} ({chartUnits})
            </h3>
          </div>

          <div className="flex-1 border border-gray-200 rounded bg-white p-4 min-h-0">
            <div className="w-full h-full">
              <ChartRenderer
                config={config}
                onSeriesToggle={() => {}}
              />
            </div>
          </div>
        </div>

        {/* Commentary Section (1/3) */}
        <div className="flex-[1] bg-gray-50 rounded border border-gray-200 p-6 flex flex-col">
          <h3 className="text-lg font-bold text-[#003d7a] mb-5">
            Key Insights
          </h3>

          <ul className="space-y-0 flex-1">
            {insights.map((insight, index) => (
              <li
                key={index}
                className="relative pl-6 py-3 text-sm leading-relaxed text-gray-800 border-b border-gray-200 last:border-b-0"
              >
                <span className="absolute left-0 top-3 text-[#003d7a] font-bold text-base">
                  ▸
                </span>
                {insight.text}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Optional Footer */}
      <div className="px-10 py-3 text-xs text-gray-400 border-t border-gray-100 flex-shrink-0">
        <div className="flex items-center gap-2">
          <div className="w-1.5 h-1.5 rounded-full bg-gray-300" />
          <span>Generated by SmartChart</span>
        </div>
      </div>
    </div>
  )
}
